version: '3.7'
services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=back
    networks:
      - backend
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/back
      - SERVER_PORT=8081
      - ACCESS_TOKEN_EXPIRE_MINUTES = 30
      - ALGORITHM = HS256
      - SECRET_KEY = 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    networks:
      - backend
    restart: always
networks:
  backend:
    driver: bridge
